version: '3.1'

services:

  mariadb-columnstore:
    #build: ./columnstore
    image: mariadb/columnstore
    #image: mariadb-columnstore:latest
    restart: always
    environment:
      MARIADB_USER: xColUser
      MARIADB_PASSWORD: xcol789
      MARIADB_ROOT_PASSWORD: rootxcol
      MARIADB_DATABASE: testdb
    ports:
      - 3310:3306
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./columnstore-data:/var/lib/columnstore
      - ./columnstore/mariadb.cnf:/etc/mysql/mariadb.cnf